### ISSUE TITLE
Update PyPI for Python 3 (Name 'reduce' is not defined)

### ISSUE THREAD

**Issue by flynnmd** [jakebian/hera#10]
I tried training a model with this on Python 3 and it crashed when the first epoch ended (and it was a long epoch too!) saying `name 'reduce' is not defined` in callback.py. It seems like this was already fixed with https://github.com/jakebian/hera/commit/62a0583c88202cc3c78ce013a351d4548efd068c, however.

Any chance heraspy could be updated on PyPI?

**Comment by jakebian** [comment]
[Updated!](https://pypi.python.org/pypi/heraspy/0.2). Let me know if it works!
