### ISSUE TITLE
Can not catch any plots in website 

### ISSUE THREAD

**Issue by welcomealcol** [jakebian/hera#17]
The server side shows that a client was connected after I run the keras example
![image](https://cloud.githubusercontent.com/assets/22414314/21633180/d65b5f36-d287-11e6-9ab9-fe3d22f4073b.png)

And the keras run as following:
![image](https://cloud.githubusercontent.com/assets/22414314/21633209/1e8f1f40-d288-11e6-949b-0420c52e5c31.png)

But I can not find the plot in my website:

![image](https://cloud.githubusercontent.com/assets/22414314/21633231/554456c2-d288-11e6-99d4-d723e3bb9d8d.png)

The hera config code pasted as below:
herasCallback = HeraCallback(
    'model-key',
    'localhost',
    4000
)
model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          verbose=1, validation_data=(X_test, Y_test), callbacks=[herasCallback])

What's wrong with me? Please could you kindly give me some information. Many thanks

**Comment by jakebian** [comment]
Did you run the client side app with `npm start`?

**Comment by welcomealcol** [comment]
Hi jakebiean, Many thanks for your kindly response. I run the client side and get my website successfully.
Best Regards and Thanks
HJ.ke
