### ISSUE TITLE
Python dependencies missing

### ISSUE THREAD

**Issue by max-vogler** [jakebian/hera#2]
I'm certainly no expert on python packaging, but it seems like the pip package is not installing its dependencies (`requests`, `socketIO-client`). I had to install them manually.

```
$ pip3 show heraspy

---
Metadata-Version: 2.0
Name: heraspy
Version: 0.0
Summary: Keras data extraction callbacks
Home-page: UNKNOWN
Author: Jake Bian
Author-email: jake@getalkanet.com
Installer: pip
License: wtfpl
Location: /usr/lib/python3.4/site-packages
Requires: 
Classifiers:
```

**Comment by jakebian** [comment]
Updated setup.py and pushed to PyPI, thanks!  https://github.com/jakebian/hera/commit/54f32e6814b90a274afb61ceb94447b46cb87c14
