### ISSUE TITLE
GIF in README is too large for some devices

### ISSUE THREAD

**Issue by ghost** [jakebian/hera#7]
Hi Jake!

Please reduce size of gif embedded to README because now it is so large that Chrome on Android crashes when I try to open the repository page. As far as I understand that's because it decompresses all frames to RAM, so their total size becomes larger than available memory.

Maybe it is better to just use a static screenshot with a link to a video on YouTube?

**Comment by jakebian** [comment]
Hey  Alex, I was concerned about this too but then found it to load  in a reasonable time in all my devices. But I think this is a fair point, can you send a PR with this change?

**Comment by ghost** [comment]
I tried to resize it with `gifsicle` but some colors look weird now. Maybe it would be better to take the source video in true color if you have one, split it to png frames and then feed to `gifsicle` in order to obtain obtain gif that doesn't suffer from resizing of dithered colors.

**Comment by jakebian** [comment]
Gif is now small  and reflects new interface
